<!--
Nombre: [Paul Andres Peley El Kadi]
Curso: [Asir1]
Fecha: [04/03/2025]
Ejercicio: [Biblioteca]
-->

<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (titulo, editorial, autor, paginas)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT editorial (#PCDATA)>
    <!ELEMENT autor (nombre, apellidos)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT paginas (#PCDATA)>
]>

<biblioteca>
    <libro>
        <titulo>El Principito</titulo>
        <editorial>Reynal Hitchcock</editorial>
        <autor>
            <nombre>Antoine</nombre>
            <apellidos>de Saint-Exupéry</apellidos>
        </autor>
        <paginas>96</paginas>
    </libro>

    <libro>
        <titulo>Cien años de soledad</titulo>
        <editorial>Editorial Sudamericana</editorial>
        <autor>
            <nombre>Gabriel</nombre>
            <apellidos>García Márquez</apellidos>
        </autor>
        <paginas>417</paginas>
    </libro>

    <libro>
        <titulo>1984</titulo>
        <editorial>Secker  Warburg</editorial>
        <autor>
            <nombre>George</nombre>
            <apellidos>Orwell</apellidos>
        </autor>
        <paginas>328</paginas>
    </libro>
</biblioteca>